# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Team OptoFab :handshake: TechLauncher"
description: "@ANU 2021 Semester 2"
# baseurl: # the subpath of your site, e.g. "/blog"
# baseurl:
# url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
url: https://optofab.github.io
# logo: # path of site logo, e.g. "/images/logo.png"
logo: "/images/ANFFlogo.png"
date_format: "%B %-d, %Y"
# read_time: # reading time estimates, e.g. true
read_time: true
# words_per_minute: # 200
words_per_minute: 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo: # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags: # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
# google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-2M6G855D7E"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

paginate: 10 # amount of posts to show per page
paginate_path: /page:num/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  - scope:
      path: ""
      type: "workrecords"
    values:
      layout: "workrecord"
      share: true

# remember when creating a new folder, add it to the collections for output html files; otherwise it won't show
collections:
  "meetings":
    output: true
  "workrecords":
    output: true
  "retrospectives":
    output: true
  "projectstatus":
    output: true
  "decisionlogs":
    output: true

# Site Author
author:
  name: Team OptoFab @TechLauncher
  picture: "/images/team-avatar.jpg"
  email: "optofab.anu@gmail.com"
  twitter:
  links:
    - title: YouTube
      url: https://www.youtube.com/channel/UCIIsJ4_yAvgD5NCqGoS8TQA
      icon: fab fa-youtube
    - title: Slack
      url: https://comp8715anff.slack.com
      icon: fab fa-slack

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
